# Generated by Django 6.1 on 2026-08-13 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_alter_projectstatus_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
