# Generated by Django 6.1 on 2026-08-19 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_sprint'),
        ('issues', '0011_alter_issue_space_alter_issue_sprint'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterUniqueTogether(
                    name='projectstatus',
                    unique_together=None,
                ),
                migrations.RemoveField(
                    model_name='projectstatus',
                    name='project',
                ),
                migrations.RemoveField(
                    model_name='projectstatus',
                    name='space',
                ),
                migrations.RemoveField(
                    model_name='space',
                    name='created_by',
                ),
                migrations.RemoveField(
                    model_name='space',
                    name='project',
                ),
                migrations.RemoveField(
                    model_name='sprint',
                    name='space',
                ),
                migrations.RemoveField(
                    model_name='userprofile',
                    name='user',
                ),
                migrations.DeleteModel(
                    name='Page',
                ),
                migrations.DeleteModel(
                    name='ProjectStatus',
                ),
                migrations.DeleteModel(
                    name='Space',
                ),
                migrations.DeleteModel(
                    name='Sprint',
                ),
                migrations.DeleteModel(
                    name='UserProfile',
                ),
            ],
            database_operations=[]
        )
    ]
