# Generated by Django 6.1 on 2026-08-10 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_projectstatus'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='projectstatus',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='projectstatus',
            name='space',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='projects.space'),
        ),
        migrations.AlterField(
            model_name='projectstatus',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='projects.project'),
        ),
        migrations.AlterUniqueTogether(
            name='projectstatus',
            unique_together={('space', 'code')},
        ),
    ]
