# Generated by Django 6.1 on 2026-08-19 11:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0009_sprint'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='Space',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('name', models.CharField(max_length=100)),
                        ('key', models.CharField(max_length=10, unique=True)),
                        ('description', models.TextField(blank=True, default='')),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_spaces', to=settings.AUTH_USER_MODEL)),
                        ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spaces', to='projects.project')),
                    ],
                    options={
                        'db_table': 'projects_space',
                    },
                ),
                migrations.CreateModel(
                    name='Page',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('title', models.CharField(max_length=200)),
                        ('content', models.TextField(blank=True)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_pages', to=settings.AUTH_USER_MODEL)),
                        ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='spaces.space')),
                    ],
                    options={
                        'db_table': 'projects_page',
                    },
                ),
                migrations.CreateModel(
                    name='Sprint',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('name', models.CharField(max_length=100)),
                        ('goal', models.TextField(blank=True, default='')),
                        ('status', models.CharField(choices=[('PL', 'Planning'), ('AC', 'Active'), ('CO', 'Completed')], default='PL', max_length=2)),
                        ('start_date', models.DateField(blank=True, null=True)),
                        ('end_date', models.DateField(blank=True, null=True)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('order', models.PositiveIntegerField(default=0)),
                        ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sprints', to='spaces.space')),
                    ],
                    options={
                        'db_table': 'projects_sprint',
                    },
                ),
                migrations.CreateModel(
                    name='ProjectStatus',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('name', models.CharField(max_length=50)),
                        ('code', models.CharField(max_length=20)),
                        ('order', models.PositiveIntegerField(default=0)),
                        ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='projects.project')),
                        ('space', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='spaces.space')),
                    ],
                    options={
                        'db_table': 'projects_projectstatus',
                        'ordering': ['order', 'id'],
                        'unique_together': {('space', 'code')},
                    },
                ),
            ],
            database_operations=[]
        )
    ]
