# Generated by Django 6.1 on 2026-08-09 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0002_remove_issue_user_issue_assignee_issue_priority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='label',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
