# Generated by Django 6.1 on 2026-08-10 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0005_alter_issue_status'),
        ('projects', '0006_projectstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='space',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues', to='projects.space'),
        ),
    ]
