# Generated by Django 6.1 on 2026-08-10 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0006_issue_space'),
        ('projects', '0007_alter_projectstatus_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='space',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='projects.space'),
        ),
    ]
