# Generated by Django 6.1 on 2026-08-13 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0007_alter_issue_space'),
        ('projects', '0009_sprint'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='sprint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues', to='projects.sprint'),
        ),
    ]
