# Generated by Django 6.1 on 2026-08-17 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0008_issue_sprint'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='story_points',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
        migrations.CreateModel(
            name='IssueLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('BL', 'Blocks'), ('BB', 'Blocked by'), ('DU', 'Duplicates'), ('RE', 'Relates to')], default='RE', max_length=2)),
                ('from_issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_links', to='issues.issue')),
                ('to_issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_links', to='issues.issue')),
            ],
            options={
                'unique_together': {('from_issue', 'to_issue', 'type')},
            },
        ),
    ]
