# Generated by Django 6.1 on 2026-08-10 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0003_issue_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='epic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_issues', to='issues.issue'),
        ),
        migrations.AddField(
            model_name='issue',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='type',
            field=models.CharField(choices=[('ST', 'Story'), ('BU', 'Bug'), ('TA', 'Task'), ('EP', 'Epic')], default='BU', max_length=2),
        ),
    ]
