# Generated by Django 6.1 on 2026-08-10 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0004_issue_due_date_issue_epic_issue_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(default='OP', max_length=20),
        ),
    ]
