# Generated by Django 6.1 on 2026-08-19 11:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='UserProfile',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('first_name', models.CharField(blank=True, max_length=150)),
                        ('last_name', models.CharField(blank=True, max_length=150)),
                        ('job_title', models.CharField(blank=True, max_length=100)),
                        ('department', models.CharField(blank=True, max_length=100)),
                        ('bio', models.TextField(blank=True)),
                        ('avatar_color', models.CharField(default='#4f46e5', max_length=7)),
                        ('phone', models.CharField(blank=True, max_length=20)),
                        ('location', models.CharField(blank=True, max_length=100)),
                        ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        'db_table': 'projects_userprofile',
                    },
                ),
            ],
            database_operations=[]
        )
    ]
